import type { AppProps } from "next/app";

import "../styles/globals.css";
import Head from "next/head";

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <div className="app">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </div>
  );
};

export default App;
